spring.application.name=insurance-claims-spring-boot

server.port=8082

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/insurance_claims_boot}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#ddl-auto=validate permits Hibernate only to validate the schema.Hibernate will not create or update tables
spring.jpa.hibernate.ddl-auto=validate

#pen-in-view=false prevents database sessions from leaking into web response rendering
spring.jpa.open-in-view=false

#Jackson property explicitly guarantees ISO-8601 date strings rather than timestamp arrays.
spring.jackson.serialization.write-dates-as-timestamps=false