package com.companyx.insuranceclaims.exception;

public enum ApiErrorCode {
	CLAIM_NOT_FOUND,
	DUPLICATE_CLAIM_NUMBER,
	VALIDATION_FAILED,
	INVALID_PAGE,
	INVALID_PAGE_SIZE,
	INVALID_STATUS_TRANSITION,
	CONCURRENT_CLAIM_UPDATE
}
